name = "hosts-generator"
compatibility_date = "2024-07-01"

[env.production]
account_id = ""
pages_build_output_dir = "dist"

[env.production.vars]
# Environment variables for production
NODE_ENV = "production"