export type Language = 'en' | 'zh';

export interface Translations {
  // Header
  appTitle: string;
  history: string;
  settings: string;
  
  // Window controls
  close: string;
  minimize: string;
  toggleFullscreen: string;
  
  // Input panel
  input: string;
  inputDescription: string;
  inputPlaceholder: string;
  resolving: string;
  resolveDomains: string;
  clear: string;
  presets: string;
  
  // Terminal
  output: string;
  outputDescription: string;
  
  // Preview
  preview: string;
  previewDescription: string;
  success: string;
  failed: string;
  total: string;
  includeLocalhost: string;
  removeComments: string;
  copy: string;
  copied: string;
  download: string;
  
  // Settings modal
  settingsTitle: string;
  presetSourceUrl: string;
  presetSourcePlaceholder: string;
  save: string;
  cancel: string;
  fetchingPresets: string;
  fetchPresetsSuccess: string;
  fetchPresetsFailed: string;
  invalidPresetFormat: string;
  
  // History
  historyTitle: string;
  clearAllRecords: string;
  loadInput: string;
  expand: string;
  collapse: string;
  inputContent: string;
  outputContent: string;
  noHistoryRecords: string;
  loading: string;
  allRecordsLoaded: string;
  confirmClearHistory: string;
  
  // Validation
  noValidDomains: string;
  invalidFormat: string;
  invalidDomainFormat: string;
  domainTooLong: string;
  validationFailed: string;
  
  // DNS Resolution
  initializingResolver: string;
  foundDomains: string;
  usingProvider: string;
  maxConcurrentRequests: string;
  resolutionCompleted: string;
  successfullyResolved: string;
  resolutionFailed: string;
  
  // Generated content
  hostsFileGenerated: string;
  generatedOn: string;
  resolvedUsing: string;
  defaultLocalhostEntries: string;
  customEntries: string;
  noHostsEntries: string;
  
  // Misc
  ready: string;
  yesterday: string;
  daysAgo: string;
  closeConfirm: string;
}

const en: Translations = {
  // Header
  appTitle: 'hosts-generator',
  history: 'History',
  settings: 'Settings',
  
  // Window controls
  close: 'Close',
  minimize: 'Minimize',
  toggleFullscreen: 'Toggle Fullscreen',
  
  // Input panel
  input: 'INPUT',
  inputDescription: 'Enter domains or hosts entries',
  inputPlaceholder: 'example.com\ngoogle.com\ngithub.com\n\n# Or paste hosts entries:\n127.0.0.1 localhost',
  resolving: 'RESOLVING...',
  resolveDomains: 'RESOLVE DOMAINS',
  clear: 'CLEAR',
  presets: 'Presets',
  
  // Terminal
  output: 'OUTPUT',
  outputDescription: 'Real-time resolution log',
  
  // Preview
  preview: 'PREVIEW',
  previewDescription: 'Generated hosts file content',
  success: 'Success',
  failed: 'Failed',
  total: 'Total',
  includeLocalhost: 'Include localhost entries',
  removeComments: 'Remove comments',
  copy: 'Copy',
  copied: 'Copied!',
  download: 'Download',
  
  // Settings modal
  settingsTitle: 'Settings',
  presetSourceUrl: 'Preset Source URL',
  presetSourcePlaceholder: 'Enter URL to fetch preset configurations...',
  save: 'Save',
  cancel: 'Cancel',
  fetchingPresets: 'Fetching presets...',
  fetchPresetsSuccess: 'Presets fetched successfully',
  fetchPresetsFailed: 'Failed to fetch presets',
  invalidPresetFormat: 'Invalid preset format',
  
  // History
  historyTitle: 'History',
  clearAllRecords: 'Clear All Records',
  loadInput: 'Load Input',
  expand: 'Expand',
  collapse: 'Collapse',
  inputContent: 'Input Content:',
  outputContent: 'Output Content:',
  noHistoryRecords: 'No history records',
  loading: 'Loading...',
  allRecordsLoaded: 'All records loaded',
  confirmClearHistory: 'Are you sure you want to clear all history records? This action cannot be undone.',
  
  // Validation
  noValidDomains: 'No valid domains found',
  invalidFormat: 'Invalid format',
  invalidDomainFormat: 'Invalid domain format',
  domainTooLong: 'Domain too long',
  validationFailed: 'Validation failed. Please fix errors and try again.',
  
  // DNS Resolution
  initializingResolver: 'Initializing DNS resolver...',
  foundDomains: 'Found {count} domains to resolve',
  usingProvider: 'Using {provider} DNS over HTTPS',
  maxConcurrentRequests: 'Max concurrent requests: 5',
  resolutionCompleted: 'DNS resolution completed.',
  successfullyResolved: 'Successfully resolved {success}/{total} domains',
  resolutionFailed: 'Resolution process failed',
  
  // Generated content
  hostsFileGenerated: 'Hosts file generated by hosts-generator',
  generatedOn: 'Generated on',
  resolvedUsing: 'Resolved using {provider} DNS over HTTPS',
  defaultLocalhostEntries: 'Default localhost entries',
  customEntries: 'Custom entries',
  noHostsEntries: 'No hosts entries generated yet\nResolve some domains to see the output here',
  
  // Misc
  ready: 'Ready to process domains...',
  yesterday: 'Yesterday',
  daysAgo: '{days} days ago',
  closeConfirm: 'Are you sure you want to close the application?'
};

const zh: Translations = {
  // Header
  appTitle: 'hosts生成器',
  history: '历史记录',
  settings: '设置',
  
  // Window controls
  close: '关闭',
  minimize: '最小化',
  toggleFullscreen: '切换全屏',
  
  // Input panel
  input: '输入',
  inputDescription: '输入域名或hosts条目',
  inputPlaceholder: 'example.com\ngoogle.com\ngithub.com\n\n# 或粘贴hosts条目:\n127.0.0.1 localhost',
  resolving: '解析中...',
  resolveDomains: '解析域名',
  clear: '清空',
  presets: '预设',
  
  // Terminal
  output: '输出',
  outputDescription: '实时解析日志',
  
  // Preview
  preview: '预览',
  previewDescription: '生成的hosts文件内容',
  success: '成功',
  failed: '失败',
  total: '总计',
  includeLocalhost: '包含localhost条目',
  removeComments: '移除注释',
  copy: '复制',
  copied: '已复制!',
  download: '下载',
  
  // Settings modal
  settingsTitle: '设置',
  presetSourceUrl: '预设源URL',
  presetSourcePlaceholder: '输入获取预设配置的URL...',
  save: '保存',
  cancel: '取消',
  fetchingPresets: '获取预设中...',
  fetchPresetsSuccess: '预设获取成功',
  fetchPresetsFailed: '预设获取失败',
  invalidPresetFormat: '预设格式无效',
  
  // History
  historyTitle: '历史记录',
  clearAllRecords: '清空所有记录',
  loadInput: '加载输入',
  expand: '展开',
  collapse: '收起',
  inputContent: '输入内容:',
  outputContent: '输出内容:',
  noHistoryRecords: '暂无历史记录',
  loading: '加载中...',
  allRecordsLoaded: '已加载所有记录',
  confirmClearHistory: '确定要清空所有历史记录吗？此操作不可撤销。',
  
  // Validation
  noValidDomains: '未找到有效域名',
  invalidFormat: '格式无效',
  invalidDomainFormat: '域名格式无效',
  domainTooLong: '域名过长',
  validationFailed: '验证失败。请修复错误后重试。',
  
  // DNS Resolution
  initializingResolver: '初始化DNS解析器...',
  foundDomains: '找到 {count} 个域名待解析',
  usingProvider: '使用 {provider} DNS over HTTPS',
  maxConcurrentRequests: '最大并发请求数: 5',
  resolutionCompleted: 'DNS解析完成。',
  successfullyResolved: '成功解析 {success}/{total} 个域名',
  resolutionFailed: '解析过程失败',
  
  // Generated content
  hostsFileGenerated: '由hosts生成器生成的Hosts文件',
  generatedOn: '生成时间',
  resolvedUsing: '使用 {provider} DNS over HTTPS 解析',
  defaultLocalhostEntries: '默认localhost条目',
  customEntries: '自定义条目',
  noHostsEntries: '尚未生成hosts条目\n解析一些域名以查看输出',
  
  // Misc
  ready: '准备处理域名...',
  yesterday: '昨天',
  daysAgo: '{days}天前',
  closeConfirm: '确定要关闭应用程序吗？'
};

export const translations = { en, zh };

export const getSystemLanguage = (): Language => {
  const lang = navigator.language.toLowerCase();
  return lang.startsWith('zh') ? 'zh' : 'en';
};

export const t = (key: keyof Translations, lang: Language, params?: Record<string, string | number>): string => {
  let text = translations[lang][key];
  
  if (params) {
    Object.entries(params).forEach(([param, value]) => {
      text = text.replace(`{${param}}`, String(value));
    });
  }
  
  return text;
};